export const Events = [{
    id: 1,
    resourceId: 'monday',
    end: '',
    classNames: ['event-thermostat'],
    coldTemperature: 23,
    hotTemperature: 45,
    type: 'sleep'
}, {
    id: 2,
    resourceId: 'wednesday',
    classNames: ['event-thermostat'],
    coldTemperature: 1,
    type: 'home',
    hotTemperature: 19
}, {
    id: 3,
    resourceId: 'tuesday',
    start: '2019-02-28T09:00:00',
    classNames: ['event-thermostat'],
    coldTemperature: 30,
    type: 'home',
    hotTemperature: 67
}, {
    id: 4,
    resourceId: 'tuesday',
    start: '2019-02-28T13:00:00',
    classNames: ['event-thermostat'],
    coldTemperature: 0,
    type: 'settings',
    hotTemperature: 36
}];