export const SvgIcons = [{
    name: 'auto',
    path: '/assets/ic_auto.svg'
}, {
    name: 'cool',
    path: '/assets/ic_cool.svg'
}, {
    name: 'heat',
    path: '/assets/ic_heat.svg'
}, {
    name: 'home',
    path: '/assets/ic_home.svg'
}, {
    name: 'moon',
    path: '/assets/ic_moon.svg'
}, {
    name: 'off',
    path: '/assets/ic_off.svg'
}, {
    name: 'outDoor',
    path: '/assets/ic_outdoor.svg'
}, {
    name: 'question',
    path: '/assets/ic_question.svg'
}, {
    name: 'questionAll',
    path: '/assets/ic_question_all.svg'
}, {
    name: 'questionRect',
    path: '/assets/ic_rectangle_question.svg'
}];
